-- MySQL Script generated by MySQL Workbench
-- Thu Oct 27 16:57:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PORTFOLIO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PORTFOLIO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PORTFOLIO` DEFAULT CHARACTER SET utf8 ;
USE `PORTFOLIO` ;

-- -----------------------------------------------------
-- Table `PORTFOLIO`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO`.`persona` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `apellido` VARCHAR(50) NULL,
  `profesion` VARCHAR(50) NULL,
  `localidad` VARCHAR(50) NULL,
  `sobre_mi` VARCHAR(1000) NULL,
  `url_foto` VARCHAR(1000) NULL,
  `url_portada` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO`.`tipo_de_empleo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO`.`tipo_de_empleo` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO`.`experiencia_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO`.`experiencia_laboral` (
  `id` INT NOT NULL,
  `puesto` VARCHAR(50) NULL,
  `descripcion` VARCHAR(1000) NULL,
  `es_trabajo_actual` TINYINT NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `url_logo_empresa` VARCHAR(1000) NULL,
  `persona_id` INT NOT NULL,
  `tipo_de_empleo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`, `tipo_de_empleo_id`),
  INDEX `fk_experiencia_laboral_persona1_idx` (`persona_id` ASC) VISIBLE,
  INDEX `fk_experiencia_laboral_tipo_de_empleo1_idx` (`tipo_de_empleo_id` ASC) VISIBLE,
  CONSTRAINT `fk_experiencia_laboral_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `PORTFOLIO`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experiencia_laboral_tipo_de_empleo1`
    FOREIGN KEY (`tipo_de_empleo_id`)
    REFERENCES `PORTFOLIO`.`tipo_de_empleo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO`.`educacion` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(50) NULL,
  `descripcion` VARCHAR(1000) NULL,
  `cursa_actualmente` TINYINT NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `url_logo_institucion` VARCHAR(1000) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_Educación_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Educación_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `PORTFOLIO`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO`.`tipo_de_habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO`.`tipo_de_habilidad` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO`.`habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO`.`habilidad` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `porcentaje_de_dominio` INT NULL,
  `persona_id` INT NOT NULL,
  `tipo_de_habilidad_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`, `tipo_de_habilidad_id`),
  INDEX `fk_habilidad_persona1_idx` (`persona_id` ASC) VISIBLE,
  INDEX `fk_habilidad_tipo_de_habilidad1_idx` (`tipo_de_habilidad_id` ASC) VISIBLE,
  CONSTRAINT `fk_habilidad_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `PORTFOLIO`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_habilidad_tipo_de_habilidad1`
    FOREIGN KEY (`tipo_de_habilidad_id`)
    REFERENCES `PORTFOLIO`.`tipo_de_habilidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO`.`proyecto` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `descripcion` VARCHAR(1000) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `url_imagen` VARCHAR(1000) NULL,
  `url_proyecto` VARCHAR(1000) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_proyecto_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_proyecto_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `PORTFOLIO`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
